// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "arduino.h"


void button1klik(lv_event_t * e)
{
	Serial.println("button1klik");
}





