// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_version;
extern lv_obj_t * ui_Tijdstempel;
extern lv_obj_t * ui_Aanvoer;
extern lv_obj_t * ui_Afvoer;
extern lv_obj_t * ui_Woonkamer;
extern lv_obj_t * ui_Luchtdruk;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

